### ISSUE TITLE
Ref: https://www.facebook.com/groups/homeassistantgroupefrance/posts/1341826740040898/

### ISSUE THREAD

**Issue by mathieucarbou** [Libertycrash91/Liberty_HA#1]
![image](https://github.com/Libertycrash91/Liberty_HA/assets/61346/54a49b73-318e-49a6-bc5c-6dfd2ba62dea)

https://github.com/Libertycrash91/Liberty_HA/blob/fb7ab38b2ee2212d0043a39b96fafbdd97ce470f/sensors.yaml#L539-L545

```yaml
template:
  # https://www.home-assistant.io/integrations/sensor/
  - sensor:
      - name: Hue Motion Sensor Hall Battery Level
        state_class: measurement
        device_class: battery
        unit_of_measurement: "%"
        state: '{{state_attr("binary_sensor.capteur_couloir_motion", "battery_level")}}'

homeassistant:
  customize:
    sensor. hue_motion_sensor_hall_battery_level:
      templates:
        icon: >
          if state_attr("binary_sensor.capteur_couloir_motion", "battery_level") <= 5
              return 'mdi:battery-outline'
          if state_attr("binary_sensor.capteur_couloir_motion", "battery_level") >= 95
              return 'mdi:battery'
          return 'mdi:battery-' + state_attr("binary_sensor.capteur_couloir_motion", "battery_level")|float / 10)|round*10}}
        icon_color: >
          [...]
```

_(not tested)_

Ref: https://www.home-assistant.io/integrations/template/

![image](https://github.com/Libertycrash91/Liberty_HA/assets/61346/2574c05a-6245-4330-998a-a1efd00c53f2)

Template declaration and UI / icons are separated. You can have everything in 1 file if you use `packages`
